spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:      simple:        default-requeue-rejected: false
  application:
    name: dsmigrationbatchtriggerconsumer
  profiles:
    active: dev
      
migration:
    application:
      username: migrationuser
      password: mIgratIonpassword1
    queue: 
      name: CORE_BATCH_TRIGGER_QUEUE
      ttl: 2000
      failure:
        retrylimit: 2
    exchange:
      name: MIGRATION_EXCHANGE
    routing:
      key: CORE_BATCH_TRIGGER_QUEUE
    processstartqueue:
      name: CORE_PARALLEL_PROCESS_START_QUEUE
      senddelay: 2000
      messagespergroup: 2
      threadpoolsize: 10
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8190/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

dsmigrationprontodata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
        
dsmigrationcoredata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"