spring:
  application:
    name: dsmigrationeurekaserver
server:
  port: 8190

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8190/eureka/
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always  endpoints:    web:      exposure:        include: "*"