spring:
  application:
    name: dsmigrationauthentication
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8190/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

#mIgratIonpassword1
migration:
  application:
    username: migrationuser
    password: 0c008ca6764a3cc230c541a7a99b0f8359dc5ef918c17d12c0292cca4250dea95e1f26271a7e30a6
    dsenvironment: account-d.docusign.com

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

ds:
  authorization:
    rsaPrivateKeyPath: /Users/pedro.barroso/dev/migration/ds-private.key
    rsaPublicKeyPath: /Users/pedro.barroso/dev/migration/ds-public.key
  migration:
    api:
      integratorKey: 8d72617c-675f-40e2-8f2e-439e5d2e95b2
    token:
      expirationSeconds: 3600
      cacheExpirationSeconds: 4
      testtoken: 