spring:
  application:
    name: dsmigrationcoredata
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testing1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${mig.peer1-address}/eureka,http://${mig.peer2-address}/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.cache.use_second_level_cache: true
spring.jpa.hibernate.cache.use_query_cache: true
spring.jpa.hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
spring.main.allow-bean-definition-overriding: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

migration:
  application:
    username: migrationuser
    password: 0c008ca6764a3cc230c541a7a99b0f8359dc5ef918c17d12c0292cca4250dea95e1f26271a7e30a6
    hazelcast:
      lockduration: 5000

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"