spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: dsmigrationadmintool
  profiles:
    active: prod
      
migration:
    application:
      username: migrationuser
      password: 0c008ca6764a3cc230c541a7a99b0f8359dc5ef918c17d12c0292cca4250dea95e1f26271a7e30a6
    processcompletequeue: 
      name: CORE_PARALLEL_PROCESS_END_QUEUE
    processstartqueue: 
      name: CORE_PARALLEL_PROCESS_START_QUEUE
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://${mig.peer1-address}/eureka,http://${mig.peer2-address}/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

feign.client.config.default.connectTimeout: 3000000
feign.client.config.default.readTimeout: 3000000
        
dsmigrationcoredata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 30000
    ReadTimeout: 30000

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"