spring:
  application:
    name: dsmigrationwebsite
  profiles:
    active: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://${mig.peer1-address}/eureka,http://${mig.peer2-address}/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

feign.client.config.default.connectTimeout: 2000000
feign.client.config.default.readTimeout: 2000000

dsmigrationauthentication:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 30000
    ReadTimeout: 30000

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

oracle:
  ibis:
    api:
      url: https://a6af0687-e9ae-432b-ab9b-e78021542430.mock.pstmn.io/api/v3/documents
    jwt:
      url: https://a6af0687-e9ae-432b-ab9b-e78021542430.mock.pstmn.io/api/v2
      user: user1
      password: password1

docusign:
  api:
    integratorKey: ROSEY_KEY
    scopes: signature impersonation
    user: 8e7f66a5-50c1-498c-8513-c403a35ea3cb
    baserUrl: http://hyousif01.hqtest.tst/restapi
    account: fdfa3ab1-2559-4c18-9d20-fc056e4f8cbe