spring:
  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: ${spring.rabbitmq.virtual-host}
  application:
    name: dsmigrationshell
  profiles:
     active: dev
    
migration:
    application:
      username: migrationuser
      password: mIgratIonpassword1
    queue: 
      name: CORE_BATCH_TRIGGER_QUEUE
      ttl: 2000
      failure:
        retrylimit: 2
    exchange:
      name: MIGRATION_EXCHANGE
    routing:
      key: CORE_BATCH_TRIGGER_QUEUE
    validatecount:
      queues: CORE_AUDIT_DATA_QUEUE,CORE_BATCH_TRIGGER_QUEUE,CORE_PARALLEL_PROCESS_END_QUEUE,CORE_PARALLEL_PROCESS_START_QUEUE,SAVE_DOCUSIGNID_MIGRATION_QUEUE,SAVE_DOCUSIGNID_PRONTO_QUEUE,HOLD_CORE_PARALLEL_PROCESS_START_QUEUE